name: gift_fund
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  flutter_gen: ^5.10.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  generate: true

  assets:
    - assets/icons/

  uses-material-design: true
